### ISSUE TITLE
Trans/Endtrans general tags

### ISSUE THREAD

**Issue by NKPmedia** [pbnl/ScoTooBo#37]
Put every general trans tags into the general group (general.asdf).

For example:

- name
- price
- gid
- id
- description

**Comment by bone4** [comment]
ToDo: add 4 missing translations for /users/add

de | messages | 1 | Stamm | Stamm
de | messages | 1 | Ambronen | Ambronen
de | messages | 1 | Hagen von Tronje | Hagen von Tronje
de | messages | 1 | Anduril | Anduril
