### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bone4** [pbnl/ScoTooBo#38]
The user should have the possibility to send feedback (remarks, errors, bugs, ...) to the developers over a feedback-button on each page.

**Comment by bone4** [comment]
added HTML include

ToDo: add server side implementation, see ScoTooBo/app/Resources/views/includes/feedback.html.twig line 7: url:'/'

**Comment by NKPmedia** [comment]
Added a server side recaptcha implementation. We now need the client side implementation.
https://developers.google.com/recaptcha/docs/display#js_api

You can set the siteSecret in the parameters.yml (see parameters.vml.dist) at
reCaptcha.secret

And the globalCode at
reCaptcha.globalCode:
Ask me for the codes

The base.html.twig already includes the js code.

You can user {{ reCaptchaGlobalCode }} in the twig templates to use the global code from the paramenters

**Comment by bone4** [comment]
Das Feedbackfenster besteht aus Feldern und Buttons (kein Formular), zudem wird jeder Seite zunächst generiert und existiert nicht einfach ausgeblendet im Hintergrund.
Ich bekomme das Google ReCaptcha daher leider nicht eingebunden, ohne das GESAMTE Frontend neu zu entwickeln.

**Comment by NKPmedia** [comment]
Ich glaube das ReCaptcha kann man auch so benutzen:
```
grecaptcha.render(
container,
parameters
)
```
um es in einem z.B. Div zu rendern.

```
grecaptcha.getResponse(
opt_widget_id
)
```
Um den respons zu bekommen. Dann brauchst du kein Form.

**Comment by NKPmedia** [comment]
So :) ReCaptcha geht jetzt. Die Tests müssen noch verbessert werden. Doch da weiß ich noch nicht ganz, wie wir die gut machen können. Da ja eine Anfrage an den Google Server gestellt wird, sind alle Test fehlerhaft. Können wir dir Anfrage irgendwie mocken!?

**Comment by bone4** [comment]
Let us use more meaningful HTTP status codes like 403 instead of 500 in the controller
