### ISSUE TITLE
Replace template with the bootstrap dashboard template

### ISSUE THREAD

**Issue by NKPmedia** [pbnl/ScoTooBo#54]
https://getbootstrap.com/docs/4.0/examples/dashboard/

Menu like:
https://getbootstrap.com/docs/4.0/examples/offcanvas/

**Comment by bone4** [comment]
Please take a look at my branch. Can we do more now?

**Comment by NKPmedia** [comment]
Looks good already. But maybe we should remove the container to use more space?

**Comment by bone4** [comment]
In der Navbar kann ich leider kein Grid anwenden, sodass dort jetzt die volle Breite genutzt wird (beim Content und Footer ist bei maximaler Größe links und rechts eine freie Spalte).

Kommentieren wir eigentlich in Deutsch oder Englisch?

**Comment by bone4** [comment]
Hast du weitere Ideen oder Wünsche? Sonst bin ich durch und erstelle demnächst einen Pull-Request.
