### ISSUE TITLE
Feedback pages are not going on

### ISSUE THREAD

**Issue by bone4** [pbnl/ScoTooBo#60]
If a user is logged in and the navbar with the codeline 

&lt;span class="navbar-toggler-icon"&gt;&lt;/span&gt;

is included, the user can't go to the secound feedback page.

GET http://html2canvas.appspot.com/?url=data%3Aimage%2Fsvg%2Bxml%3Bcharset%3Dut&callback=html2canvas_0 net::ERR_ABORTED
proxyGetImage @ html2canvas.js:2285
loadImage @ html2canvas.js:2462
getImages @ html2canvas.js:2353
getImages @ html2canvas.js:2309
getImages @ html2canvas.js:2309
getImages @ html2canvas.js:2309
getImages @ html2canvas.js:2309
_html2canvas.Preload @ html2canvas.js:2525
(anonymous) @ html2canvas.js:2772
setTimeout (async)
html2canvas @ html2canvas.js:2771
runH2c @ feedback.js:762
(anonymous) @ feedback.js:789

**Comment by NKPmedia** [comment]
Wissen wir, dass es an der class navbar-toggler-icon liegt?

**Comment by bone4** [comment]
Nur durch ausprobieren wusste ich, dass es daran lag. Mal sehen, wie es sich entwickelt, wenn wir bootstrap4 benutzen. Ich verstehe auch noch nicht, was wirklich den Fehler verursacht.

**Comment by bone4** [comment]
Bestehende Warnung im Chrome:
> [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M67, around May 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

Bestehende Warnung im Firefox:
> Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
> Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
> Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
